### ISSUE TITLE
javascript MQTT client for Sparkplug

### ISSUE THREAD

**Issue by ubunturtu** [eclipse/tahu#16]
I'm using the Javascript library and noticed that it does not use any of the MQTT client connect options namely clean session, QOS, or retain messages. Please advise if this is the case and if there are any future plans to allow these to be configured. I am particularly interested in using the retain flag on NBIRTH messages.

**Comment by ckienle** [comment]
This is intentional. In the Sparkplug specification the only "retained" messages are the STATE messages that are used for the primary application session tracking.  NBIRTH (or any other) messages should never be retained due to the even driven nature of Sparkplug and the real-time session tracking of devices.  The QoS of the STATE messages is 1, but all others is 0. The clean session flag is not explicitly discussed in the specification but is always set to true.  We will updating the specification soon, adding clarification to some of these concepts.
