### ISSUE TITLE
Host Birth Death Sequence Clarification with 3.0 STATE Payload

### ISSUE THREAD

**Issue by bryce-nakatani** [eclipse/tahu#224]
In a Sparkplug Host that implements the 3.0 host STATE and has multiple connections to MQTT Servers, is the host bdSeq global to all of the host connections or to each host connection.

The implication is that if the host loses one of the MQTT Server connections, the next connection increments bdSeq. 

If the bdSeq is global, then the other active connections must disconnect and reconnect to refresh the last will and testament's bdSeq. 

If bdSeq is local, specific to the MQTT Server, then only the STATE changes for that Server's LWT and STATE publication.

Which implementation does the specification imply, a global or a local Server bdSeq implementation?

**Comment by wes-johnson** [comment]
It turned out to be difficult to rely on a STATE bdSeq number - a new and improved solution is the simply use a timestamp in the STATE payload. If the incoming timestamp is newer or equal to the old, then it MUST be honored by the Edge Node. This also means that initial Host connections MUST use the same timestamp in the MQTT CONNECT packet as well as in the BIRTH message. It also must never update the timestamp on any sort of Rebirth that exceeds the DEATH timestamp
