### ISSUE TITLE
Allow a SCADA host to set the tags published by the EoN

### ISSUE THREAD

**Issue by jlschrag** [eclipse/tahu#25]
In Sparkplub B, the metric list published in DBIRTH is dictated completely by the EoN.  In some cases, the list of potential tags is in the thousands.  Of course, the EoN can be configured to publish only a subset of these tags, but with device counts also potentially in the thousands, manually configuring all of these tags could be time prohibitive.  Also, in many cases, users will already have a host system which contains such a tag list, and maintaining a copy in the EoN is also problematic.

It would be tremendously helpful if Sparkplug included a specification for a host to provide a list of tags it would like to be published.  This could be published to a topic similar to DCMD, and the tags could be removed from the publish list when that host went offline.

**Comment by wes-johnson** [comment]
This is also another good suggestion for discussion in the Sparkplug Working Group.  Sparkplug certainly took the view of the 'edge as the source of truth' but that certainly isn't always the case.  I could see this being expanded to include this use case you suggest.  I'd recommend looking at the working group charter.  Since this now lives in the realm of the Eclipse Foundation all spec changes will occur here:
https://www.eclipse.org/org/workinggroups/eclipse_sparkplug_charter.php
