### ISSUE TITLE
Mismatch between encoding and decoding DataSets using js

### ISSUE THREAD

**Issue by suneab** [eclipse/tahu#316]
When encoding DataSets using `encodeDataSet`, the `setValue` function is used which points to the "default" types which is `enum DataType` in `sparkplug_b.proto`
When decoding DataSets using `decodeDataSet` , the `getDataSetValue` function is used which points to the correct types which is `DataSetValue` in `sparkplug_b.proto`

This mismatch was introduced by this commit: https://github.com/eclipse/tahu/commit/59d162907ea569e80075eef2668da0ebffb1978d 
which fixed the decode function to the correct types.

A function to encode datasets correctly is missing

**Comment by suneab** [comment]
@ferm10n is this something you would be interested in fixing as well?

**Comment by ferm10n** [comment]
Hey @suneab sorry for taking forever to reply, I'm not really wired into github notifications (there's so much noise!) and only just now saw the mention.

I'm trying to recall how this stuff works... When `decodeDataSet` is called, it calls `getDataSetValue` which has no `case` for type `8` (UInt64). In the commit you linked that I authored, I wrote:
> they can't all share the metric getValue, because they can have different possible values.

For some reason I thought DataSets didn't accept all the same value types as a normal metric. But after looking through the spec I don't see that. So maybe the fix is to replace calls to `getDataSetValue` with `getValue`. That'd make sense because `encodeDataSet` calls `setValue`, and doesn't have a special fn to encode the value just for datasets.

I'll create a PR that removes `getDataSetValue` and `getTemplateParamValue`, and replace the calls with `getValue`.

------

UPDATE: while writing the PR I re-discovered why I made variations of the `getValue` for datasets and template params! The sparkplug spec says any type should be allowed, but `sparkplug_b.proto` only allows encoding a subset of types that a normal metric value can have. So does that mean that `sparkplug_b.proto` is wrong? Or is the spec itself inconsistent?

Section *6.4.11. DataSet* says
> [The] values in the types array MUST be one of the enumerated values as shown in the Sparkplug Basic Data Types.

Which would include having datasets within a dataset for example.

HOWEVER, section *6.4.1. Google Protocol Buffer Schema* has:
```proto
message DataSetValue {
    oneof value {
        uint32 int_value                        = 1;
        uint64 long_value                       = 2;
        float  float_value                      = 3;
        double double_value                     = 4;
        bool   boolean_value                    = 5;
        string string_value                     = 6;
        DataSetValueExtension extension_value   = 7;
    }
    // ...
}
```

with no way to encode things like `bytes`, `DataSet`, and `Template`.

<details>
<summary>
Here's the Metric value definition for comparison
</summary>

```proto
message Metric {
    // ...
    oneof value {
        uint32   int_value                      = 10;
        uint64   long_value                     = 11;
        float    float_value                    = 12;
        double   double_value                   = 13;
        bool     boolean_value                  = 14;
        string   string_value                   = 15;
        bytes    bytes_value                    = 16;       // Bytes, File
        DataSet  dataset_value                  = 17;
        Template template_value                 = 18;
        MetricValueExtension extension_value    = 19;
    }
}
```
</details>

--------------

Regardless, I can expand the cases for `getDataSetValue` and `getTemplateParamValue`.
