### ISSUE TITLE
Sparkplug add Alarm config

### ISSUE THREAD

**Issue by tjgrob** [eclipse/tahu#59]
I have been testing the python example. Generating Tags, reading and writing is fine however I would like to config the alarm of a tag so as a Boolean true would trigger an Alarm. Can that be added to the metric?

**Comment by wes-johnson** [comment]
It depends on what you're using to consume the metrics. Are you using Ignition or something else? Properties are not well defined in Sparkplug because there are multiple different consumers and producers of data. If using Ignition and MQTT Engine, you can only include alarm properties if using Ignition8 as the consuming application. This is not supported in Ignition7. Even in Ignition8 by default, they are filtered and this must be enabled in the configuration via the filtered properties MQTT Engine config. If these conditions are met, you can use the 'Binding/Scripting Name' from here to set the properties in the BIRTH messages. https://docs.inductiveautomation.com/display/DOC80/Tag+Alarm+Properties
